ARG K6_SEMVER=1.1.0
ARG K6_VERSION=v${K6_SEMVER}
ARG XK6_VERSION=1.0.1

FROM alpine:3.19.1 AS builder

RUN apk add --update \
 python3 \
 curl \
 which \
 bash

RUN curl -sSL https://sdk.cloud.google.com | bash


FROM grafana/k6:${K6_SEMVER}
ARG K6_VERSION
ARG XK6_VERSION
USER root

RUN apk add --update python3 uuidgen sed go git

COPY --from=builder /root/google-cloud-sdk /root/google-cloud-sdk

ENV PATH=$PATH:/root/google-cloud-sdk/bin
ENV K6_VERSION=${K6_VERSION}

RUN mkdir k6
RUN mkdir /home/apis

# k6.tar.gz is created by make to get around .dockerignore
ADD k6.tar.gz k6/
# copy protos
ADD apis /home/apis/

WORKDIR k6

RUN go install go.k6.io/xk6/cmd/xk6@v${XK6_VERSION}
RUN ~/go/bin/xk6 build --with github.com/grafana/xk6-kubernetes

RUN mkdir results

RUN chmod +x k6wrapper.sh
ENTRYPOINT ["./k6wrapper.sh", "run"]

ARG GIT_COMMIT=${GIT_COMMIT}
ARG GIT_BRANCH=${GIT_COMMIT}
ENV GIT_COMMIT=${GIT_COMMIT}
ENV GIT_BRANCH=${GIT_BRANCH}

# should be overriden in practice
CMD ["-u", "5", "scenarios/infer_constant_vu.js"]
