FROM alpine:3.6 AS builder

RUN apk add --update --no-cache python curl which bash && \
    curl -sSL https://sdk.cloud.google.com | bash

FROM grafana/k6

USER root

RUN apk add --update --no-cache python3 uuidgen sed

ENV PATH $PATH:/root/google-cloud-sdk/bin

COPY --from=builder /root/google-cloud-sdk /root/google-cloud-sdk
# k6.tar.gz is created by make to get around .dockerignore
ADD k6.tar.gz k6/
# copy protos
ADD apis /home/apis/

WORKDIR k6

RUN mkdir results && \
    chmod +x k6wrapper.sh

ENV GIT_COMMIT ${GIT_COMMIT}
ENV GIT_BRANCH ${GIT_BRANCH}

# should be overriden in practice
ENTRYPOINT ["./k6wrapper.sh", "run"]
CMD ["-u", "5", "scenarios/infer_constant_vu.js"]
