#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

if [ ! -f "${STARTUP_DIR}/../settings.sh" ]; then
    echo "settings.sh not found!"
    exit 1
fi
source ${STARTUP_DIR}/../settings.sh

helm reset --kube-context="${KUBE_CONTEXT}"

