#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

if [ ! -f "${STARTUP_DIR}/../settings.sh" ]; then
    cp -v "${STARTUP_DIR}/../settings.sh.example" "${STARTUP_DIR}/../settings.sh"
fi
source ${STARTUP_DIR}/../settings.sh

helm reset --kube-context="${KUBE_CONTEXT}"

