#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/../settings.sh
SELDON_CORE_DIR=${STARTUP_DIR}/../../..

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

# add seldon crd access to admin role
 ${KUBECTL} apply -f ${STARTUP_DIR}/seldon-aggregate-to-admin.json

helm install --kube-context="${KUBE_CONTEXT}" ${SELDON_CORE_DIR}/helm-charts/seldon-core-crd --name seldon-core-crd --set usage_metrics.enabled=true
helm install --kube-context="${KUBE_CONTEXT}" ${SELDON_CORE_DIR}/helm-charts/seldon-core \
        --name seldon-core \
        --set apife_service_type=ClusterIP \
        --set ambassador.enabled=true \
        --namespace default

