#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/../settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

POD_NAME=$(${KUBECTL} get pods -l app=docker-private-registry -n default |sed -e '1d'|awk '{print $1}') && ${KUBECTL} port-forward ${POD_NAME} 5000:5000 -n default

