#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/../settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

${KUBECTL} apply -f ${STARTUP_DIR}/docker-private-registry.json -n default
${KUBECTL} rollout status deploy/docker-private-registry-deployment -n default
${KUBECTL} apply -f ${STARTUP_DIR}/docker-private-registry-proxy.json -n default

