#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/../settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

${KUBECTL} delete -f ${STARTUP_DIR}/docker-private-registry.json --ignore-not-found=true -n default
${KUBECTL} delete -f ${STARTUP_DIR}/docker-private-registry-proxy.json --ignore-not-found=true -n default

