FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN microdnf update -y && \
    microdnf install -y \
      wget \
      bzip2 \
      tar \
      ca-certificates \
      curl-minimal \
      findutils

# MPL based licenses
RUN wget -O certifi-python-certifi.tar.gz \
    https://github.com/certifi/python-certifi/archive/master.tar.gz

# Install Miniforge (BSD-3-Clause)
# Fix vulnerabilities for brotli and h2
# Fix vulnerability in pip(9CVE-2025-8869)
ARG MINIFORGE_VERSION
RUN wget https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE_VERSION}/Miniforge3-${MINIFORGE_VERSION}-Linux-x86_64.sh -O ~/miniforge.sh && \
    /bin/bash ~/miniforge.sh -b -p /opt/conda && \
    rm ~/miniforge.sh && \
    /opt/conda/bin/conda init bash && \
    /opt/conda/bin/conda install -c conda-forge "brotli>=1.2.0,<1.3.0" "h2>=4.3.0,<4.4.0" -y && \
    /opt/conda/bin/pip install "pip>=25.3,<26.0" && \
    /opt/conda/bin/conda clean -afy && \
    rm -rf /opt/conda/pkgs && \
    find /opt/conda -type f -name '*.a' -delete && \
    find /opt/conda -type f -name '*.pyc' -delete && \
    find /opt/conda -type f -name '*.js.map' -delete && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    chgrp -R root /opt/conda && chmod -R g+rw /opt/conda

# Replace conda's python ensurepip with correct version
RUN PIP_WHEEL_DIR=/opt/conda/lib/python3.12/ensurepip/_bundled && \
    /opt/conda/bin/pip wheel "pip==25.3.0" "setuptools>=75.0.0,<76.0.0" "wheel>=0.44.0,<0.45.0" --wheel-dir $PIP_WHEEL_DIR && \
    rm -f $PIP_WHEEL_DIR/pip-25.0.1-py3-none-any.whl

ENV TINI_VERSION v0.16.1
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT [ "/usr/bin/tini", "--" ]

CMD [ "/bin/bash" ]
