FROM continuumio/miniconda3:%CONDA_VERSION%

LABEL io.openshift.s2i.scripts-url="image:///s2i/bin"

# This is to install desired version of Python without updating conda version
RUN conda install --yes python=%PYTHON_VERSION% conda=%CONDA_VERSION%
RUN apt-get update --yes && apt-get install --yes make

RUN mkdir microservice
WORKDIR /microservice

COPY ./s2i/bin/ /s2i/bin

# keep install of seldon-core after the COPY to force re-build of layer
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

EXPOSE 5000
