FROM python:%PYTHON_VERSION%

LABEL io.openshift.s2i.scripts-url="image:///s2i/bin"

RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential

RUN mkdir microservice
WORKDIR /microservice

RUN pip install seldon-core

COPY ./s2i/bin/ /s2i/bin

EXPOSE 5000
