FROM openvino_base:latest
LABEL io.openshift.s2i.scripts-url="image:///s2i/bin"

#RUN apt-get update -y
RUN apt-get install -y build-essential

RUN mkdir microservice
WORKDIR /microservice

ENV LD_LIBRARY_PATH=/usr/local/lib
ENV PYTHONPATH=/usr/local/lib

RUN conda create --name myenv -y
ENV PATH /opt/conda/envs/myenv/bin:$PATH

COPY _python /microservice

RUN cd /microservice/python && \
    pip install .

#RUN pip install seldon-core

COPY ./s2i/bin/ /s2i/bin

EXPOSE 5000
