/*
Copyright 2019 The Seldon Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"github.com/seldonio/seldon-core/operator/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type V1alpha2Interface interface {
	RESTClient() rest.Interface
	SeldonDeploymentsGetter
}

// V1alpha2Client is used to interact with features provided by the v1alpha2 group.
type V1alpha2Client struct {
	restClient rest.Interface
}

func (c *V1alpha2Client) SeldonDeployments(namespace string) SeldonDeploymentInterface {
	return newSeldonDeployments(c, namespace)
}

// NewForConfig creates a new V1alpha2Client for the given config.
func NewForConfig(c *rest.Config) (*V1alpha2Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &V1alpha2Client{client}, nil
}

// NewForConfigOrDie creates a new V1alpha2Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *V1alpha2Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new V1alpha2Client for the given RESTClient.
func New(c rest.Interface) *V1alpha2Client {
	return &V1alpha2Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	config.APIPath = "/apis"
	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
	if config.GroupVersion == nil || config.GroupVersion.Group != scheme.Scheme.PrioritizedVersionsForGroup("v1alpha2")[0].Group {
		gv := scheme.Scheme.PrioritizedVersionsForGroup("v1alpha2")[0]
		config.GroupVersion = &gv
	}
	config.NegotiatedSerializer = scheme.Codecs

	if config.QPS == 0 {
		config.QPS = 5
	}
	if config.Burst == 0 {
		config.Burst = 10
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *V1alpha2Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
