#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

cd "$STARTUP_DIR"

docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $HOME/.m2:/root/.m2 \
    -v $PWD:/work \
    seldonio/core-builder:0.7 bash -c 'make -f Makefile.ci build'

