#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

MAVEN_REPOSITORY_LOCATION=/tmp/.m2/repository

PLATFORM_ARGS=()
if [[ -n "${RELEASE_DOCKER_PLATFORM:-}" ]]; then
    PLATFORM_ARGS+=(--platform="${RELEASE_DOCKER_PLATFORM}")
elif [[ "$(uname -m)" != "x86_64" ]]; then
    PLATFORM_ARGS+=(--platform=linux/amd64)
fi

docker run --rm -it \
    "${PLATFORM_ARGS[@]}" \
    --user=$(id -u):$(id -g) \
    -e MAVEN_REPOSITORY_LOCATION=${MAVEN_REPOSITORY_LOCATION} \
    -v ${HOME}/.m2/repository:${MAVEN_REPOSITORY_LOCATION} \
    -v "${STARTUP_DIR}":/work \
    seldonio/core-builder:0.31 python release.py "$@"
