#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

#cd "${STARTUP_DIR}/api-frontend"	&& make stop_apife_istio
cd "${STARTUP_DIR}/api-frontend"	&& make stop_apife
cd "${STARTUP_DIR}/cluster-manager"	&& make stop_cluster_manager
cd "${STARTUP_DIR}/kafka"   && make stop_kafka
cd "${STARTUP_DIR}/zookeeper-k8s"	&& make stop_zookeeper
cd "${STARTUP_DIR}/redis-memonly"   && make stop_redis


