/*
Copyright (c) 2024 Seldon Technologies Ltd.

Use of this software is governed BY
(1) the license included in the LICENSE file or
(2) if the license included in the LICENSE file is the Business Source License 1.1,
the Change License after the Change Date as each is defined in accordance with the LICENSE file.
*/

// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v2_dataplane.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.seldon.mlops.inference.v2;

@kotlin.jvm.JvmName("-initializemodelMetadataResponse")
public inline fun modelMetadataResponse(block: io.seldon.mlops.inference.v2.ModelMetadataResponseKt.Dsl.() -> kotlin.Unit): io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse =
  io.seldon.mlops.inference.v2.ModelMetadataResponseKt.Dsl._create(io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `inference.ModelMetadataResponse`
 */
public object ModelMetadataResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse = _builder.build()

    /**
     * ```
     * The model name.
     * ```
     *
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * ```
     * The model name.
     * ```
     *
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class VersionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The versions of the model available on the server.
     * ```
     *
     * `repeated string versions = 2;`
     * @return A list containing the versions.
     */
    public val versions: com.google.protobuf.kotlin.DslList<kotlin.String, VersionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getVersionsList()
      )
    /**
     * ```
     * The versions of the model available on the server.
     * ```
     *
     * `repeated string versions = 2;`
     * @param value The versions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addVersions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, VersionsProxy>.add(value: kotlin.String) {
      _builder.addVersions(value)
    }
    /**
     * ```
     * The versions of the model available on the server.
     * ```
     *
     * `repeated string versions = 2;`
     * @param value The versions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignVersions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, VersionsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * The versions of the model available on the server.
     * ```
     *
     * `repeated string versions = 2;`
     * @param values The versions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllVersions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, VersionsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllVersions(values)
    }
    /**
     * ```
     * The versions of the model available on the server.
     * ```
     *
     * `repeated string versions = 2;`
     * @param values The versions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllVersions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, VersionsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * The versions of the model available on the server.
     * ```
     *
     * `repeated string versions = 2;`
     * @param index The index to set the value at.
     * @param value The versions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setVersions")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, VersionsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setVersions(index, value)
    }/**
     * ```
     * The versions of the model available on the server.
     * ```
     *
     * `repeated string versions = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearVersions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, VersionsProxy>.clear() {
      _builder.clearVersions()
    }
    /**
     * ```
     * The model's platform. See Platforms.
     * ```
     *
     * `string platform = 3;`
     */
    public var platform: kotlin.String
      @JvmName("getPlatform")
      get() = _builder.getPlatform()
      @JvmName("setPlatform")
      set(value) {
        _builder.setPlatform(value)
      }
    /**
     * ```
     * The model's platform. See Platforms.
     * ```
     *
     * `string platform = 3;`
     */
    public fun clearPlatform() {
      _builder.clearPlatform()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class InputsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The model's inputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata inputs = 4;`
     */
     public val inputs: com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, InputsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getInputsList()
      )
    /**
     * ```
     * The model's inputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata inputs = 4;`
     * @param value The inputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addInputs")
    public fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, InputsProxy>.add(value: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata) {
      _builder.addInputs(value)
    }
    /**
     * ```
     * The model's inputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata inputs = 4;`
     * @param value The inputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignInputs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, InputsProxy>.plusAssign(value: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata) {
      add(value)
    }
    /**
     * ```
     * The model's inputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata inputs = 4;`
     * @param values The inputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllInputs")
    public fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, InputsProxy>.addAll(values: kotlin.collections.Iterable<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata>) {
      _builder.addAllInputs(values)
    }
    /**
     * ```
     * The model's inputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata inputs = 4;`
     * @param values The inputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllInputs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, InputsProxy>.plusAssign(values: kotlin.collections.Iterable<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata>) {
      addAll(values)
    }
    /**
     * ```
     * The model's inputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata inputs = 4;`
     * @param index The index to set the value at.
     * @param value The inputs to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setInputs")
    public operator fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, InputsProxy>.set(index: kotlin.Int, value: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata) {
      _builder.setInputs(index, value)
    }
    /**
     * ```
     * The model's inputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata inputs = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearInputs")
    public fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, InputsProxy>.clear() {
      _builder.clearInputs()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OutputsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The model's outputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata outputs = 5;`
     */
     public val outputs: com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, OutputsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getOutputsList()
      )
    /**
     * ```
     * The model's outputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata outputs = 5;`
     * @param value The outputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOutputs")
    public fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, OutputsProxy>.add(value: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata) {
      _builder.addOutputs(value)
    }
    /**
     * ```
     * The model's outputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata outputs = 5;`
     * @param value The outputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOutputs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, OutputsProxy>.plusAssign(value: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata) {
      add(value)
    }
    /**
     * ```
     * The model's outputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata outputs = 5;`
     * @param values The outputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOutputs")
    public fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, OutputsProxy>.addAll(values: kotlin.collections.Iterable<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata>) {
      _builder.addAllOutputs(values)
    }
    /**
     * ```
     * The model's outputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata outputs = 5;`
     * @param values The outputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOutputs")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, OutputsProxy>.plusAssign(values: kotlin.collections.Iterable<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata>) {
      addAll(values)
    }
    /**
     * ```
     * The model's outputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata outputs = 5;`
     * @param index The index to set the value at.
     * @param value The outputs to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOutputs")
    public operator fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, OutputsProxy>.set(index: kotlin.Int, value: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata) {
      _builder.setOutputs(index, value)
    }
    /**
     * ```
     * The model's outputs.
     * ```
     *
     * `repeated .inference.ModelMetadataResponse.TensorMetadata outputs = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOutputs")
    public fun com.google.protobuf.kotlin.DslList<io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata, OutputsProxy>.clear() {
      _builder.clearOutputs()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ParametersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Optional default parameters for the request / response.
     * NOTE: This is an extension to the standard
     * ```
     *
     * `map<string, .inference.InferParameter> parameters = 6;`
     */
     public val parameters: com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getParametersMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getParametersMap()
      )
    /**
     * ```
     * Optional default parameters for the request / response.
     * NOTE: This is an extension to the standard
     * ```
     *
     * `map<string, .inference.InferParameter> parameters = 6;`
     */
    @JvmName("putParameters")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
      .put(key: kotlin.String, value: io.seldon.mlops.inference.v2.V2Dataplane.InferParameter) {
         _builder.putParameters(key, value)
       }
    /**
     * ```
     * Optional default parameters for the request / response.
     * NOTE: This is an extension to the standard
     * ```
     *
     * `map<string, .inference.InferParameter> parameters = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setParameters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
      .set(key: kotlin.String, value: io.seldon.mlops.inference.v2.V2Dataplane.InferParameter) {
         put(key, value)
       }
    /**
     * ```
     * Optional default parameters for the request / response.
     * NOTE: This is an extension to the standard
     * ```
     *
     * `map<string, .inference.InferParameter> parameters = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeParameters")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
      .remove(key: kotlin.String) {
         _builder.removeParameters(key)
       }
    /**
     * ```
     * Optional default parameters for the request / response.
     * NOTE: This is an extension to the standard
     * ```
     *
     * `map<string, .inference.InferParameter> parameters = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllParameters")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter>) {
         _builder.putAllParameters(map)
       }
    /**
     * ```
     * Optional default parameters for the request / response.
     * NOTE: This is an extension to the standard
     * ```
     *
     * `map<string, .inference.InferParameter> parameters = 6;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearParameters")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
      .clear() {
         _builder.clearParameters()
       }
  }
  @kotlin.jvm.JvmName("-initializetensorMetadata")
  public inline fun tensorMetadata(block: io.seldon.mlops.inference.v2.ModelMetadataResponseKt.TensorMetadataKt.Dsl.() -> kotlin.Unit): io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata =
    io.seldon.mlops.inference.v2.ModelMetadataResponseKt.TensorMetadataKt.Dsl._create(io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Metadata for a tensor.
   * ```
   *
   * Protobuf type `inference.ModelMetadataResponse.TensorMetadata`
   */
  public object TensorMetadataKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata = _builder.build()

      /**
       * ```
       * The tensor name.
       * ```
       *
       * `string name = 1;`
       */
      public var name: kotlin.String
        @JvmName("getName")
        get() = _builder.getName()
        @JvmName("setName")
        set(value) {
          _builder.setName(value)
        }
      /**
       * ```
       * The tensor name.
       * ```
       *
       * `string name = 1;`
       */
      public fun clearName() {
        _builder.clearName()
      }

      /**
       * ```
       * The tensor data type.
       * ```
       *
       * `string datatype = 2;`
       */
      public var datatype: kotlin.String
        @JvmName("getDatatype")
        get() = _builder.getDatatype()
        @JvmName("setDatatype")
        set(value) {
          _builder.setDatatype(value)
        }
      /**
       * ```
       * The tensor data type.
       * ```
       *
       * `string datatype = 2;`
       */
      public fun clearDatatype() {
        _builder.clearDatatype()
      }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class ShapeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * ```
       * The tensor shape. A variable-size dimension is represented
       * by a -1 value.
       * ```
       *
       * `repeated int64 shape = 3;`
       */
       public val shape: com.google.protobuf.kotlin.DslList<kotlin.Long, ShapeProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.getShapeList()
        )
      /**
       * ```
       * The tensor shape. A variable-size dimension is represented
       * by a -1 value.
       * ```
       *
       * `repeated int64 shape = 3;`
       * @param value The shape to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addShape")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Long, ShapeProxy>.add(value: kotlin.Long) {
        _builder.addShape(value)
      }/**
       * ```
       * The tensor shape. A variable-size dimension is represented
       * by a -1 value.
       * ```
       *
       * `repeated int64 shape = 3;`
       * @param value The shape to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignShape")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Long, ShapeProxy>.plusAssign(value: kotlin.Long) {
        add(value)
      }/**
       * ```
       * The tensor shape. A variable-size dimension is represented
       * by a -1 value.
       * ```
       *
       * `repeated int64 shape = 3;`
       * @param values The shape to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllShape")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Long, ShapeProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Long>) {
        _builder.addAllShape(values)
      }/**
       * ```
       * The tensor shape. A variable-size dimension is represented
       * by a -1 value.
       * ```
       *
       * `repeated int64 shape = 3;`
       * @param values The shape to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllShape")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Long, ShapeProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Long>) {
        addAll(values)
      }/**
       * ```
       * The tensor shape. A variable-size dimension is represented
       * by a -1 value.
       * ```
       *
       * `repeated int64 shape = 3;`
       * @param index The index to set the value at.
       * @param value The shape to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setShape")
      public operator fun com.google.protobuf.kotlin.DslList<kotlin.Long, ShapeProxy>.set(index: kotlin.Int, value: kotlin.Long) {
        _builder.setShape(index, value)
      }/**
       * ```
       * The tensor shape. A variable-size dimension is represented
       * by a -1 value.
       * ```
       *
       * `repeated int64 shape = 3;`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearShape")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Long, ShapeProxy>.clear() {
        _builder.clearShape()
      }
      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class ParametersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * ```
       * Optional default parameters for input.
       * NOTE: This is an extension to the standard
       * ```
       *
       * `map<string, .inference.InferParameter> parameters = 4;`
       */
       public val parameters: com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
        @kotlin.jvm.JvmSynthetic
        @JvmName("getParametersMap")
        get() = com.google.protobuf.kotlin.DslMap(
          _builder.getParametersMap()
        )
      /**
       * ```
       * Optional default parameters for input.
       * NOTE: This is an extension to the standard
       * ```
       *
       * `map<string, .inference.InferParameter> parameters = 4;`
       */
      @JvmName("putParameters")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
        .put(key: kotlin.String, value: io.seldon.mlops.inference.v2.V2Dataplane.InferParameter) {
           _builder.putParameters(key, value)
         }
      /**
       * ```
       * Optional default parameters for input.
       * NOTE: This is an extension to the standard
       * ```
       *
       * `map<string, .inference.InferParameter> parameters = 4;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("setParameters")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
        .set(key: kotlin.String, value: io.seldon.mlops.inference.v2.V2Dataplane.InferParameter) {
           put(key, value)
         }
      /**
       * ```
       * Optional default parameters for input.
       * NOTE: This is an extension to the standard
       * ```
       *
       * `map<string, .inference.InferParameter> parameters = 4;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("removeParameters")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
        .remove(key: kotlin.String) {
           _builder.removeParameters(key)
         }
      /**
       * ```
       * Optional default parameters for input.
       * NOTE: This is an extension to the standard
       * ```
       *
       * `map<string, .inference.InferParameter> parameters = 4;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("putAllParameters")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
        .putAll(map: kotlin.collections.Map<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter>) {
           _builder.putAllParameters(map)
         }
      /**
       * ```
       * Optional default parameters for input.
       * NOTE: This is an extension to the standard
       * ```
       *
       * `map<string, .inference.InferParameter> parameters = 4;`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("clearParameters")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, io.seldon.mlops.inference.v2.V2Dataplane.InferParameter, ParametersProxy>
        .clear() {
           _builder.clearParameters()
         }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.copy(block: `io.seldon.mlops.inference.v2`.ModelMetadataResponseKt.Dsl.() -> kotlin.Unit): io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse =
  `io.seldon.mlops.inference.v2`.ModelMetadataResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata.copy(block: `io.seldon.mlops.inference.v2`.ModelMetadataResponseKt.TensorMetadataKt.Dsl.() -> kotlin.Unit): io.seldon.mlops.inference.v2.V2Dataplane.ModelMetadataResponse.TensorMetadata =
  `io.seldon.mlops.inference.v2`.ModelMetadataResponseKt.TensorMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

