FROM {{ base_image }}
{% for key,value in kwargs.iteritems() %}
LABEL "{{ key }}"="{{ value }}"{% endfor %}

RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential

COPY /requirements.txt /tmp/
COPY /seldon_requirements.txt /tmp/
RUN cd /tmp && \
    pip install --no-cache-dir -r seldon_requirements.txt && \
    pip install --no-cache-dir -r requirements.txt

RUN mkdir microservice
COPY ./ /microservice/
WORKDIR /microservice

EXPOSE 5000
CMD ["python","-u","microservice.py","{{ model_name }}","{{ api_type }}","--service-type","{{ service_type }}","--persistence","{{ persistence }}"]
