FROM python:2

RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential

RUN mkdir microservice
COPY ./* /microservice/
WORKDIR /microservice

RUN pip install --no-cache-dir -r seldon_requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
CMD ["python","{api_type}_microservice.py","{model_name}"]
