{
 "title": "Seldon Core Model Mesh Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Models",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (seldon_mesh_seldon_loaded_model_memory_bytes_gauge >0 )",
     "legendFormat": "In-memory"
    },
    {
     "expr": "sum (seldon_mesh_seldon_loaded_model_gauge)",
     "legendFormat": "Registered"
    }
   ]
  },
  {
   "title": "Registered Model Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server) (seldon_mesh_seldon_loaded_model_gauge)"
    }
   ]
  },
  {
   "title": "In-Memory Model Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(server) (seldon_mesh_seldon_loaded_model_memory_bytes_gauge > 0)"
    }
   ]
  },
  {
   "title": "In-Memory Model Replicas (Memory Slots)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server) (seldon_mesh_seldon_loaded_model_memory_bytes_gauge) / sum by(server) (seldon_mesh_seldon_server_replica_memory_capacity_overcommit_bytes_gauge)"
    }
   ]
  },
  {
   "title": "Model Evict Rate [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(seldon_mesh_seldon_cache_evict_count[1m]))",
     "legendFormat": "Evict Rate"
    }
   ]
  },
  {
   "title": "Model Miss Rate [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(seldon_mesh_seldon_cache_miss_count[1m]))",
     "legendFormat": "Miss Rate"
    }
   ]
  },
  {
   "title": "Memory Slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(seldon_mesh_seldon_server_replica_memory_capacity_bytes_gauge)",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(seldon_mesh_seldon_loaded_model_memory_bytes_gauge)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(seldon_mesh_seldon_server_replica_memory_capacity_overcommit_bytes_gauge)",
     "legendFormat": "Capacity with Over-commit"
    },
    {
     "expr": "sum(seldon_mesh_seldon_loaded_model_memory_bytes_gauge) + sum(seldon_mesh_seldon_evicted_model_memory_bytes_gauge)",
     "legendFormat": "Used with Over-commit"
    }
   ]
  },
  {
   "title": "Infer Latency (avg[1m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.9, \n(\nrate(seldon_mesh_seldon_infer_seconds_total{container=\"agent\"}[1m]) / rate(seldon_mesh_seldon_infer_total{container=\"agent\"}[1m])\n)\n) by (server)",
     "legendFormat": "{{server}}_90%"
    },
    {
     "expr": "quantile(0.5, \n(\nrate(seldon_mesh_seldon_infer_seconds_total{container=\"agent\"}[10m]) / rate(seldon_mesh_seldon_infer_total{container=\"agent\"}[10m])\n)\n) by (server)",
     "legendFormat": "{{server}}_50%"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"mlserver\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container=\"triton\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Rate [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{container=\"mlserver\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate (container_cpu_usage_seconds_total{container=\"triton\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}