pipeline {
    parameters {
        booleanParam(name: 'PUBLISH_IMAGE', defaultValue: false, description: '')
    }
    agent {
        docker {
            image 'seldonio/core-builder:0.4'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        SELDON_CORE_DOCKER_HUB_USER = credentials('SELDON_CORE_DOCKER_HUB_USER')
        SELDON_CORE_DOCKER_HUB_PASSWORD = credentials('SELDON_CORE_DOCKER_HUB_PASSWORD')
    }
    stages {
        stage('build-engine') {
            steps {
                echo "Build Image"
                sh 'cd engine && make -f Makefile.ci build'
            }
        }
        stage('publish-image') {
            when {
                expression { return params.PUBLISH_IMAGE == true }
            }
            steps {
                script {
                    echo "Publishing Image"
                    sh 'cd engine && make -f Makefile.ci repo_login'
                    sh 'cd engine && make -f Makefile.ci push_image'
                }
            }
        }
    }
}

