pipeline {
    parameters {
        booleanParam(name: 'PUBLISH_IMAGE', defaultValue: false, description: '')
    }
    agent {
        docker {
            image 'seldonio/core-builder:0.3'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        SELDON_CORE_DOCKER_HUB_USER = credentials('SELDON_CORE_DOCKER_HUB_USER')
        SELDON_CORE_DOCKER_HUB_PASSWORD = credentials('SELDON_CORE_DOCKER_HUB_PASSWORD')
    }
    stages {
        stage('build-engine') {
            steps {
                echo "Build Image"
                sh 'cd engine && make -f Makefile.ci build'
                script {
                    if (params.PUBLISH_IMAGE == true) {
                        echo "Publish Image"
                        sh 'cd engine && make -f Makefile.ci repo_login'
                        sh 'cd engine && make -f Makefile.ci push_image'
                    } else {
                        echo "Publish Image [SKIPPED]"
                    }
                }
            }
        }
    }
}

