build_jar: update_proto
	mvn clean package -B

clean:
	mvn clean -B
	rm -fv src/main/proto/seldon_deployment.proto
	rm -fv src/main/proto/prediction.proto

update_proto:
	cp -v ../proto/seldon_deployment.proto src/main/proto/
	cp -v ../proto/prediction.proto src/main/proto/

