ARG IMAGE_SOURCE=openjdk:13.0.1-jdk-buster
FROM $IMAGE_SOURCE

RUN apt-get upgrade && \
        apt-get update

RUN mkdir /build

LABEL io.openshift.s2i.scripts-url="image:///s2i/bin"
LABEL io.openshift.s2i.assemble-input-files="/build"

COPY ./s2i/bin/ /s2i/bin

WORKDIR /microservice

EXPOSE 5000

