#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

kubectl create configmap --dry-run grafana-import-dashboards --from-file=${STARTUP_DIR}/configs/ --output yaml > ${STARTUP_DIR}/_configmap.yaml

