#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/../settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

#JENKINS_CHART_VERSION=0.15.1
JENKINS_CHART_VERSION=0.19.1

helm install --kube-context="${KUBE_CONTEXT}" stable/jenkins \
    --name jenkins \
    --namespace jenkins \
    --set rbac.install=true \
    --version $JENKINS_CHART_VERSION \
    --set Master.AdminUser=admin \
    --set Master.AdminPassword=admin

# create a rolebing for jenkins
${KUBECTL} create rolebinding jenkins-admin --clusterrole=admin --serviceaccount=jenkins:default --namespace=default --dry-run -o yaml | \
    ${KUBECTL} apply -f -

