#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/../settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

helm delete --kube-context="${KUBE_CONTEXT}" jenkins --purge||echo "ignore"

${KUBECTL} delete rolebinding jenkins-admin --ignore-not-found

