#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/../settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

${KUBECTL} logs -f $(kubectl --context="${KUBE_CONTEXT}" get pods -n default -l app=activity-monitor -o jsonpath='{.items[0].metadata.name}') -n default

