/*
Copyright (c) 2024 Seldon Technologies Ltd.

Use of this software is governed BY
(1) the license included in the LICENSE file or
(2) if the license included in the LICENSE file is the Business Source License 1.1,
the Change License after the Change Date as each is defined in accordance with the LICENSE file.
*/

package fsm

import (
	"context"
	"fmt"
)

// todo: we could do our tradicional locking too but for this to probably work we would need a manager to do the updates
// todo: the manager would then lock the entire Handle of an event and do its processing, could become a little bit of a problem when having many status updates from Agents
// KVStore interface for state persistence with optimistic locking
type KVStore interface {
	// Get retrieves value and current version
	Get(ctx context.Context, key string) (value []byte, version int64, err error)
	// Set without version check (for initial writes)
	Set(ctx context.Context, key string, value []byte) (int64, error)
	Delete(ctx context.Context, key string) error
}

// Event represents an incoming event to the FSM
type Event interface {
	Type() EventType
	Marshal() ([]byte, error)
}

type EventType string

const (
	EventTypeLoadModel   EventType = "LoadModel"
	EventTypeUnloadModel EventType = "UnloadModel"
)

// OutputEvent represents events generated by the FSM for downstream consumers
type OutputEvent interface {
	Type() string
}

// Fsm is the finite state machine that processes events
type Fsm struct {
	name     string
	store    KVStore
	handlers map[EventType]Handler
}

type Handler interface {
	Handle(ctx context.Context, ev Event) ([]OutputEvent, error)
}

func NewFSM(name string, store KVStore) *Fsm {
	fsm := &Fsm{
		name:     name,
		store:    store,
		handlers: make(map[EventType]Handler),
	}

	// Register default handlers
	fsm.RegisterHandler(EventTypeLoadModel, NewLoadModelEventHandler(store))

	return fsm
}

func (f *Fsm) RegisterHandler(eventType EventType, handler Handler) {
	f.handlers[eventType] = handler
}

// Apply processes an event through the FSM
// 1. Applies business logic and updates KVStore
// 2. Generates output events
func (f *Fsm) Apply(ctx context.Context, event Event) ([]OutputEvent, error) {

	// 2. Get handler for this event type
	handler, exists := f.handlers[event.Type()]
	if !exists {
		return nil, fmt.Errorf("no handler registered for event type: %s", event.Type())
	}

	// 3. Process event and update KVStore
	outputEvents, err := handler.Handle(ctx, event)
	if err != nil {
		return nil, fmt.Errorf("handler failed: %w", err)
	}

	return outputEvents, nil
}
