#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/../settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

EXTERNAL_IP=$(${KUBECTL} get svc -n argocd argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

echo ""
echo "Payload URL: https://${EXTERNAL_IP}/api/webhook"
echo "Content type: application/json"
echo "Secret: RANDTOKEN"
echo "SSL verification: Disable"
echo ""

