// Code generated by MockGen. DO NOT EDIT.
// Source: file_manager.go
//
// Generated by this command:
//
//	mockgen -source=file_manager.go -destination=./mocks/mock_file_manager.go -package=mocks FileManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileManager is a mock of FileManager interface.
type MockFileManager struct {
	ctrl     *gomock.Controller
	recorder *MockFileManagerMockRecorder
}

// MockFileManagerMockRecorder is the mock recorder for MockFileManager.
type MockFileManagerMockRecorder struct {
	mock *MockFileManager
}

// NewMockFileManager creates a new mock instance.
func NewMockFileManager(ctrl *gomock.Controller) *MockFileManager {
	mock := &MockFileManager{ctrl: ctrl}
	mock.recorder = &MockFileManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileManager) EXPECT() *MockFileManagerMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockFileManager) Config(config []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config", config)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config.
func (mr *MockFileManagerMockRecorder) Config(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockFileManager)(nil).Config), config)
}

// Copy mocks base method.
func (m *MockFileManager) Copy(ctx context.Context, modelName, srcUri string, config []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, modelName, srcUri, config)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Copy indicates an expected call of Copy.
func (mr *MockFileManagerMockRecorder) Copy(ctx, modelName, srcUri, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockFileManager)(nil).Copy), ctx, modelName, srcUri, config)
}

// DeleteRemote mocks base method.
func (m *MockFileManager) DeleteRemote(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRemote", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRemote indicates an expected call of DeleteRemote.
func (mr *MockFileManagerMockRecorder) DeleteRemote(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRemote", reflect.TypeOf((*MockFileManager)(nil).DeleteRemote), name)
}

// ListRemotes mocks base method.
func (m *MockFileManager) ListRemotes() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRemotes")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRemotes indicates an expected call of ListRemotes.
func (mr *MockFileManagerMockRecorder) ListRemotes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRemotes", reflect.TypeOf((*MockFileManager)(nil).ListRemotes))
}

// PurgeLocal mocks base method.
func (m *MockFileManager) PurgeLocal(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeLocal", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurgeLocal indicates an expected call of PurgeLocal.
func (mr *MockFileManagerMockRecorder) PurgeLocal(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeLocal", reflect.TypeOf((*MockFileManager)(nil).PurgeLocal), path)
}

// Ready mocks base method.
func (m *MockFileManager) Ready() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ready indicates an expected call of Ready.
func (mr *MockFileManagerMockRecorder) Ready() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockFileManager)(nil).Ready))
}

// StartConfigListener mocks base method.
func (m *MockFileManager) StartConfigListener() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartConfigListener")
	ret0, _ := ret[0].(error)
	return ret0
}

// StartConfigListener indicates an expected call of StartConfigListener.
func (mr *MockFileManagerMockRecorder) StartConfigListener() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartConfigListener", reflect.TypeOf((*MockFileManager)(nil).StartConfigListener))
}
