HEADER_RETURN_INSTANCE_SCORE = "Alibi-Detect-Return-Instance-Score"
HEADER_RETURN_FEATURE_SCORE = "Alibi-Detect-Return-Feature-Score"
ENV_RETURN_INSTANCE_SCORE = "ALIBI_DETECT_RETURN_INSTANCE_SCORE"
ENV_RETURN_FEATURE_SCORE = "ALIBI_DETECT_RETURN_FEATURE_SCORE"
ENV_DRIFT_TYPE_FEATURE = "ALIBI_DETECT_DRIFT_TYPE_FEATURE"
HEADER_OUTLIER_TYPE = "Alibi-Detect-Outlier-Type"

REQUEST_ID_HEADER_NAME = "Ce-Requestid"
NAMESPACE_HEADER_NAME = "Ce-Namespace"
