// Code generated by MockGen. DO NOT EDIT.
// Source: ./storage.go
//
// Generated by this command:
//
//	mockgen -source=./storage.go -destination=./mock/storage_reader.go -package=mock StorageReader
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	proto "google.golang.org/protobuf/proto"
)

// MockStorageReader is a mock of StorageReader interface.
type MockStorageReader[T proto.Message] struct {
	ctrl     *gomock.Controller
	recorder *MockStorageReaderMockRecorder[T]
}

// MockStorageReaderMockRecorder is the mock recorder for MockStorageReader.
type MockStorageReaderMockRecorder[T proto.Message] struct {
	mock *MockStorageReader[T]
}

// NewMockStorageReader creates a new mock instance.
func NewMockStorageReader[T proto.Message](ctrl *gomock.Controller) *MockStorageReader[T] {
	mock := &MockStorageReader[T]{ctrl: ctrl}
	mock.recorder = &MockStorageReaderMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageReader[T]) EXPECT() *MockStorageReaderMockRecorder[T] {
	return m.recorder
}

// Get mocks base method.
func (m *MockStorageReader[T]) Get(ctx context.Context, name string) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageReaderMockRecorder[T]) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorageReader[T])(nil).Get), ctx, name)
}

// List mocks base method.
func (m *MockStorageReader[T]) List(ctx context.Context) ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStorageReaderMockRecorder[T]) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStorageReader[T])(nil).List), ctx)
}

// MockStorageWriter is a mock of StorageWriter interface.
type MockStorageWriter[T proto.Message] struct {
	ctrl     *gomock.Controller
	recorder *MockStorageWriterMockRecorder[T]
}

// MockStorageWriterMockRecorder is the mock recorder for MockStorageWriter.
type MockStorageWriterMockRecorder[T proto.Message] struct {
	mock *MockStorageWriter[T]
}

// NewMockStorageWriter creates a new mock instance.
func NewMockStorageWriter[T proto.Message](ctrl *gomock.Controller) *MockStorageWriter[T] {
	mock := &MockStorageWriter[T]{ctrl: ctrl}
	mock.recorder = &MockStorageWriterMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageWriter[T]) EXPECT() *MockStorageWriterMockRecorder[T] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStorageWriter[T]) Delete(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageWriterMockRecorder[T]) Delete(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorageWriter[T])(nil).Delete), ctx, name)
}

// Insert mocks base method.
func (m *MockStorageWriter[T]) Insert(ctx context.Context, record T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockStorageWriterMockRecorder[T]) Insert(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockStorageWriter[T])(nil).Insert), ctx, record)
}

// Update mocks base method.
func (m *MockStorageWriter[T]) Update(ctx context.Context, record T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStorageWriterMockRecorder[T]) Update(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStorageWriter[T])(nil).Update), ctx, record)
}

// MockStorage is a mock of Storage interface.
type MockStorage[T proto.Message] struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder[T]
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder[T proto.Message] struct {
	mock *MockStorage[T]
}

// NewMockStorage creates a new mock instance.
func NewMockStorage[T proto.Message](ctrl *gomock.Controller) *MockStorage[T] {
	mock := &MockStorage[T]{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage[T]) EXPECT() *MockStorageMockRecorder[T] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStorage[T]) Delete(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageMockRecorder[T]) Delete(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorage[T])(nil).Delete), ctx, name)
}

// Get mocks base method.
func (m *MockStorage[T]) Get(ctx context.Context, name string) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageMockRecorder[T]) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage[T])(nil).Get), ctx, name)
}

// Insert mocks base method.
func (m *MockStorage[T]) Insert(ctx context.Context, record T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockStorageMockRecorder[T]) Insert(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockStorage[T])(nil).Insert), ctx, record)
}

// List mocks base method.
func (m *MockStorage[T]) List(ctx context.Context) ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStorageMockRecorder[T]) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStorage[T])(nil).List), ctx)
}

// Update mocks base method.
func (m *MockStorage[T]) Update(ctx context.Context, record T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStorageMockRecorder[T]) Update(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStorage[T])(nil).Update), ctx, record)
}
