/*
Copyright 2019 The Seldon Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	"time"

	v1alpha2 "github.com/seldonio/seldon-core/operator/apis/machinelearning.seldon.io/v1alpha2"
	scheme "github.com/seldonio/seldon-core/operator/client/machinelearning.seldon.io/v1alpha2/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SeldonDeploymentsGetter has a method to return a SeldonDeploymentInterface.
// A group's client should implement this interface.
type SeldonDeploymentsGetter interface {
	SeldonDeployments(namespace string) SeldonDeploymentInterface
}

// SeldonDeploymentInterface has methods to work with SeldonDeployment resources.
type SeldonDeploymentInterface interface {
	Create(ctx context.Context, seldonDeployment *v1alpha2.SeldonDeployment, opts v1.CreateOptions) (*v1alpha2.SeldonDeployment, error)
	Update(ctx context.Context, seldonDeployment *v1alpha2.SeldonDeployment, opts v1.UpdateOptions) (*v1alpha2.SeldonDeployment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.SeldonDeployment, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.SeldonDeploymentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.SeldonDeployment, err error)
	SeldonDeploymentExpansion
}

// seldonDeployments implements SeldonDeploymentInterface
type seldonDeployments struct {
	client rest.Interface
	ns     string
}

// newSeldonDeployments returns a SeldonDeployments
func newSeldonDeployments(c *MachinelearningV1alpha2Client, namespace string) *seldonDeployments {
	return &seldonDeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the seldonDeployment, and returns the corresponding seldonDeployment object, and an error if there is any.
func (c *seldonDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.SeldonDeployment, err error) {
	result = &v1alpha2.SeldonDeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("seldondeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SeldonDeployments that match those selectors.
func (c *seldonDeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.SeldonDeploymentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.SeldonDeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("seldondeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested seldonDeployments.
func (c *seldonDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("seldondeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a seldonDeployment and creates it.  Returns the server's representation of the seldonDeployment, and an error, if there is any.
func (c *seldonDeployments) Create(ctx context.Context, seldonDeployment *v1alpha2.SeldonDeployment, opts v1.CreateOptions) (result *v1alpha2.SeldonDeployment, err error) {
	result = &v1alpha2.SeldonDeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("seldondeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(seldonDeployment).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a seldonDeployment and updates it. Returns the server's representation of the seldonDeployment, and an error, if there is any.
func (c *seldonDeployments) Update(ctx context.Context, seldonDeployment *v1alpha2.SeldonDeployment, opts v1.UpdateOptions) (result *v1alpha2.SeldonDeployment, err error) {
	result = &v1alpha2.SeldonDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("seldondeployments").
		Name(seldonDeployment.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(seldonDeployment).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the seldonDeployment and deletes it. Returns an error if one occurs.
func (c *seldonDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("seldondeployments").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *seldonDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("seldondeployments").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched seldonDeployment.
func (c *seldonDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.SeldonDeployment, err error) {
	result = &v1alpha2.SeldonDeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("seldondeployments").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
