FROM golang:1.18-alpine as builder

RUN apk add --upgrade make

WORKDIR /build
ADD . .

ARG GIT_BRANCH
ARG GIT_COMMIT
ARG RELEASE_TYPE
ARG BUILD_VERSION

RUN make -C hodometer build-hodometer

################################################################################

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /build/hodometer/bin/hodometer /bin/hodometer

ARG UID=1000
ARG GID=1000
USER ${UID}:${GID}

CMD ["/bin/hodometer"]
