FROM golang:1.18-alpine AS builder

RUN apk add --upgrade make

WORKDIR /build
COPY . .

RUN make -C hodometer build-receiver

################################################################################

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /build/hodometer/bin/receiver /bin/receiver

ARG UID=1000
ARG GID=1000
USER ${UID}:${GID}

CMD ["/bin/receiver"]
