FROM golang:1.18-alpine AS builder

RUN apk add --upgrade make cmake

WORKDIR /build
COPY . .

RUN make build-receiver

################################################################################

FROM golang:1.18-alpine
COPY --from=builder /build/bin/receiver /bin/receiver

ARG UID=1000
ARG GID=1000
USER ${UID}:${GID}

CMD ["/bin/receiver"]
