/*
Copyright (c) 2024 Seldon Technologies Ltd.

Use of this software is governed BY
(1) the license included in the LICENSE file or
(2) if the license included in the LICENSE file is the Business Source License 1.1,
the Change License after the Change Date as each is defined in accordance with the LICENSE file.
*/

package events

// Event represents an incoming event to the FSM
// todo: do we need to register events that have partial state registered
type Event interface {
	Type() EventType
}

type EventType string

// todo: Child events might have different interfaces
// OutputEvent represents events generated by the FSM for downstream consumers
type OutputEvent interface {
	Type() string
}
