models: mlflowserver-models sklearnserver-models


mlflowserver-models:
	make -C mlflowserver/models/elasticnet_wine


sklearnserver-models:
	make -C sklearnserver/models/iris
	make -C sklearnserver/models/moviesentiment
