models: mlflowserver-models sklearnserver-models huggingface-models


mlflowserver-models:
	make -C mlflowserver/models/elasticnet_wine


sklearnserver-models:
	make -C sklearnserver/models/iris
	make -C sklearnserver/models/moviesentiment


huggingface-models:
	make -C huggingface/models/text-gen-gpt2
	make -C huggingface/models/text-gen-tiny-stories

