FROM openjdk:8u201-jre-alpine3.9 as builder

ARG APP_VERSION=UNKOWN_VERSION

RUN apk add curl

COPY /target/seldon-engine-${APP_VERSION}.jar /app.jar
COPY /target/generated-resources /licenses/

# Copy the controller-manager into a thin image
FROM registry.access.redhat.com/ubi8/ubi

RUN yum install java-1.8.0-openjdk.x86_64 -y

LABEL name="Seldon Engine" \
      vendor="Seldon Technologies" \
      version="v0.3.1" \
      release="1" \
      summary="The Seldon Engine that is deployed for each model to handle the data flow of each ML computational graph." \
      description="The Seldon Engine that is deployed for each model to handle the data flow of each ML computational graph."

WORKDIR /
COPY --from=builder /app.jar app.jar
COPY --from=builder /licenses/ /licenses/

entrypoint [ "sh", "-c", "java -djava.security.egd=file:/dev/./urandom $java_opts -jar app.jar" ]
