

train:
	npm install
	npm start

clean_build:
	rm -f *ubyte
	rm -rf node_modules
	rm -f package-lock.json
	
clean:
	rm -f *ubyte
	rm -rf node_modules
	rm -f package-lock.json
	rm -f model.json
	rm -f weights.bin
