#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/../settings.sh
SELDON_CORE_DIR=${STARTUP_DIR}/../../..

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

${KUBECTL} delete -f ${SELDON_CORE_DIR}/notebooks/resources/model.json -n default --ignore-not-found=true

