FROM envoyproxy/envoy:v1.19.1
COPY scheduler/config/envoy.yaml /etc/envoy.yaml
COPY scheduler/config/envoy-local.yaml /etc/envoy-local.yaml
COPY scheduler/config/envoy-compose.yaml /etc/envoy-compose.yaml
CMD /usr/local/bin/envoy -c /etc/envoy.yaml
