FROM golang:alpine as builder

RUN mkdir /build
ADD . /build/
WORKDIR /build
RUN rm -r apis && mv apis-TEMP apis

# Build the binary
RUN CGO_ENABLED=0 go build -o agent ./cmd/agent/main.go

# Copy binary
# Need to be careful about: https://github.com/GoogleContainerTools/distroless/issues/718
# for environments like Openshift that set a random UID
# if we want to use FROM gcr.io/distroless/static:noroot
# Keeping with Alpine at present to allow setting of volume permissions for Docker Compose use
# both with shared and bind mounted volumes
FROM alpine:latest
RUN addgroup -S agent && adduser -S agent -G agent
RUN mkdir /mnt/agent && chmod o+rwx /mnt/agent
VOLUME /mnt/agent
USER agent
COPY --from=builder /build/agent /bin/agent
ENTRYPOINT ["/bin/agent"]
