FROM golang:1.19.8-buster as builder

WORKDIR /build
COPY . .

# Build the binary
RUN apt-get install make
RUN make -C scheduler -o test-go build-modelgateway

# Kafka dependencies necessitate leaving CGo enabled and using a base image with C dependencies
FROM registry.access.redhat.com/ubi9/ubi-micro:9.1.0-15
COPY --from=builder /build/scheduler/bin/modelgateway /bin/modelgateway
ENTRYPOINT ["/bin/modelgateway"]
