FROM golang:1.17.1-buster as builder

WORKDIR /build
COPY . .

# Build the binary
RUN apt-get install make
RUN make -C scheduler -o test-go build-pipelinegateway

# Kafka dependencies necessitate leaving CGo enabled and using a base image with C dependencies
FROM gcr.io/distroless/base-debian11:nonroot
COPY --from=builder /build/scheduler/bin/pipelinegateway /bin/pipelinegateway
ENTRYPOINT ["/bin/pipelinegateway"]
