FROM golang:1.19.10-alpine as builder

WORKDIR /build
COPY . .

# Build the binary
RUN apk add --no-cache make
RUN make -C scheduler -o test-go build-agent

# Copy binary
FROM registry.access.redhat.com/ubi9/ubi-micro:9.1.0-15

RUN mkdir /mnt/agent && chmod o+rwx /mnt/agent
VOLUME /mnt/agent

COPY --from=builder /build/scheduler/bin/agent /bin/agent
ENTRYPOINT ["/bin/agent"]
