FROM golang:alpine as builder

RUN mkdir /build
ADD . /build/
WORKDIR /build
RUN rm -r apis && mv apis-TEMP apis

# Build the binary
RUN go build -o scheduler ./cmd/scheduler/main.go

# Copy into scratch
FROM golang:alpine
COPY --from=builder /build/scheduler /bin/scheduler
CMD ["/bin/scheduler"]