FROM golang:alpine as builder

RUN mkdir /build
ADD . /build/
WORKDIR /build

# Build the binary
RUN go build -o scheduler ./cmd/server/main.go

# Copy into scratch
FROM golang:alpine
COPY --from=builder /build/scheduler /bin/scheduler
#COPY config/seldon.yaml /config/seldon.yaml
CMD ["/bin/scheduler"]