FROM golang:1.22-bullseye as builder

WORKDIR /build
COPY . .

# Build the binary
RUN apt-get install make
RUN make -C scheduler -o test-go build-scheduler

# Kafka dependencies necessitate leaving CGo enabled and using a base image with C dependencies
FROM registry.access.redhat.com/ubi9/ubi-micro:9.3-13
COPY --from=builder /build/scheduler/bin/scheduler /bin/scheduler
ENTRYPOINT ["/bin/scheduler"]
