FROM golang:1.17.1-buster as builder

RUN mkdir /build
ADD . /build/
WORKDIR /build
RUN rm -r apis && mv apis-TEMP apis

# Build the binary
RUN go build -o stream ./cmd/stream/main.go

# Copy into scratch
FROM gcr.io/distroless/base-debian10:latest
COPY --from=builder /build/stream /bin/stream
CMD ["/bin/stream"]