#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail
set -o noclobber
set -o noglob

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

rm -fv ${STARTUP_DIR}/jenkins/jobs/build-model-images-job_config.xml.tmp
rm -fv ${STARTUP_DIR}/jenkins/jobs/get-all-job_config.xml.tmp

