#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail
set -o noclobber
set -o noglob

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

watch -t -n 1 "echo 'Every 1s: Watching Pods in default namespace' && echo '' && ${KUBECTL} get pods -n default"

