{
 "title": "Envoy Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,10m,15m,30m" },
   {
    "name": "envoy_cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_total{pod=\"$pod\"},envoy_cluster_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(envoy_server_live{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(envoy_server_memory_heap_size{namespace=\"$namespace\"}[$interval]))",
     "legendFormat": "{{pod}}-heap-size"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pod, envoy_cluster_name) (rate(envoy_http_downstream_rq_xx{namespace=\"$namespace\", envoy_response_code_class=\"5\"}[$interval]))\n/\nsum by (pod, envoy_cluster_name) (rate(envoy_http_downstream_rq_total{namespace=\"$namespace\"}[$interval]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_server_concurrency{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Downstream Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Downstream Request Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, envoy_response_code_class) (rate(envoy_http_downstream_rq_xx{namespace=\"$namespace\", pod=\"$pod\", envoy_http_conn_manager_prefix=\"http\"}[$interval]))",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Downstream Requests Active",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_http_downstream_rq_active{namespace=\"$namespace\", envoy_http_conn_manager_prefix=\"http\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Downstream Requests Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod, envoy_cluster_name) (rate(envoy_http_downstream_rq_total{namespace=\"$namespace\", envoy_http_conn_manager_prefix=\"http\", envoy_cluster_name!=\"xds_cluster\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "{{pod}}-total"
    },
    {
     "expr": "sum by (pod, envoy_cluster_name) (rate(envoy_http_downstream_rq_tx_reset{namespace=\"$namespace\", envoy_http_conn_manager_prefix=\"http\", envoy_cluster_name!=\"xds_cluster\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "{{pod}}-reset"
    }
   ]
  },
  {
   "title": "Downstream Request Time Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,  sum by (le) (rate(envoy_http_downstream_rq_time_bucket{namespace=\"$namespace\", envoy_http_conn_manager_prefix=\"http\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90,  sum by (le) (rate(envoy_http_downstream_rq_time_bucket{namespace=\"$namespace\", envoy_http_conn_manager_prefix=\"http\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50,  sum by (le) (rate(envoy_http_downstream_rq_time_bucket{namespace=\"$namespace\", envoy_http_conn_manager_prefix=\"http\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Cluster Upstream Request Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pod, envoy_cluster_name, envoy_response_code_class) (rate(envoy_cluster_upstream_rq_xx{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "{{envoy_response_code_class}}xx-{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Connections Active",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}",
     "legendFormat": "{{envoy_cluster_name}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Upstream Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "sum by (pod, envoy_cluster_name) (rate(envoy_cluster_upstream_rq{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "{{pod}}-{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Upstream Request Time Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,  sum by (le, envoy_cluster_name) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p99"
    },
    {
     "expr": "histogram_quantile(0.90,  sum by (le, envoy_cluster_name) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p90"
    },
    {
     "expr": "histogram_quantile(0.50,  sum by (le, envoy_cluster_name) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p50"
    }
   ]
  },
  {
   "title": "Cluster Upstream Connect Destroyed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by (pod, envoy_cluster_name) (rate(envoy_cluster_upstream_cx_destroy{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "{{pod}}-{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Upstream Connect Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by (pod, envoy_cluster_name) (rate(envoy_cluster_upstream_cx_connect_timeout{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "{{pod}}-{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Retry Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by (pod, envoy_cluster_name, envoy_response_code_class) (rate(envoy_cluster_upstream_rq_retry{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "total-{{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (pod, envoy_cluster_name, envoy_response_code_class) (rate(envoy_cluster_upstream_rq_retry_success{namespace=\"$namespace\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "success-{{envoy_cluster_name}}"
    }
   ]
  },
  { "title": "xDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Cluster Membership Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (envoy_cluster_membership_total{namespace=\"$namespace\", pod=\"$pod\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum (envoy_cluster_membership_healthy{namespace=\"$namespace\", pod=\"$pod\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"})",
     "legendFormat": "healthy"
    },
    {
     "expr": "sum (envoy_cluster_membership_degraded{namespace=\"$namespace\", pod=\"$pod\", envoy_cluster_name=~\"$envoy_cluster_name\", pod=\"$pod\"})",
     "legendFormat": "degraded"
    }
   ]
  },
  {
   "title": "Cluster CDS Update Duration Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,  sum by (le) (rate(envoy_cluster_manager_cds_update_duration_bucket{namespace=\"$namespace\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p99"
    },
    {
     "expr": "histogram_quantile(0.90,  sum by (le) (rate(envoy_cluster_manager_cds_update_duration_bucket{namespace=\"$namespace\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p90"
    },
    {
     "expr": "histogram_quantile(0.50,  sum by (le) (rate(envoy_cluster_manager_cds_update_duration_bucket{namespace=\"$namespace\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p50"
    }
   ]
  },
  {
   "title": "CDS Updates",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "sum (increase(envoy_cluster_manager_cluster_added{namespace=\"$namespace\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "clusters-added"
    },
    {
     "expr": "sum (increase(envoy_cluster_manager_cluster_modified{namespace=\"$namespace\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "clusters-modified"
    },
    {
     "expr": "sum (increase(envoy_cluster_manager_cluster_removed{namespace=\"$namespace\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "clusters-removed"
    }
   ]
  },
  {
   "title": "Listener LDS Update Duration Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,  sum by (le) (rate(envoy_listener_manager_lds_update_duration_bucket{namespace=\"$namespace\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p99"
    },
    {
     "expr": "histogram_quantile(0.90,  sum by (le) (rate(envoy_listener_manager_lds_update_duration_bucket{namespace=\"$namespace\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p90"
    },
    {
     "expr": "histogram_quantile(0.50,  sum by (le) (rate(envoy_listener_manager_lds_update_duration_bucket{namespace=\"$namespace\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p50"
    }
   ]
  },
  {
   "title": "LDS Updates",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum (increase(envoy_listener_manager_lds_update_success{namespace=\"$namespace\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "update-success"
    },
    {
     "expr": "sum (increase(envoy_listener_manager_lds_update_failure{namespace=\"$namespace\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "update-failure"
    },
    {
     "expr": "sum (increase(envoy_listener_manager_lds_update_rejected{namespace=\"$namespace\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "update-rejected"
    }
   ]
  },
  {
   "title": "Route RDS Update Duration Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,  sum by (le) (rate(envoy_http_rds_update_duration_bucket{namespace=\"$namespace\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p99"
    },
    {
     "expr": "histogram_quantile(0.90,  sum by (le) (rate(envoy_http_rds_update_duration_bucket{namespace=\"$namespace\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p90"
    },
    {
     "expr": "histogram_quantile(0.50,  sum by (le) (rate(envoy_http_rds_update_duration_bucket{namespace=\"$namespace\", pod=\"$pod\"}[$interval])))",
     "legendFormat": "{{envoy_cluster_name}}-p50"
    }
   ]
  },
  {
   "title": "RDS Updates",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "sum (increase(envoy_http_rds_update_success{namespace=\"$namespace\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "update-success"
    },
    {
     "expr": "sum (increase(envoy_http_rds_update_failure{namespace=\"$namespace\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "update-failure"
    },
    {
     "expr": "sum (increase(envoy_http_rds_update_rejected{namespace=\"$namespace\", pod=\"$pod\"}[$interval]))",
     "legendFormat": "update-rejected"
    }
   ]
  }
 ]
}