{
 "title": "Performance and scaling",
 "time": { "from": "2024-08-06T13:59:49.416Z", "to": "2024-08-06T15:09:30.277Z" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "inference_pods",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pod=~\"mlserver.*|triton.*\"},pod)"
    }
   },
   {
    "name": "model",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pod=~\"$inference_pods\"},model)"
    }
   },
   { "name": "rate_window", "query": "1m,3m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Per-model metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response throughput by (model, pod) (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model, pod) (rate(seldon_model_infer_total{namespace=~\"${namespace:regex}\", model=~\"${model:regex}\", pod=~\"${inference_pods:regex}\"}[${rate_window}]))",
     "legendFormat": "{{model}}, {{pod}}"
    }
   ]
  },
  {
   "title": "REST average latency (agent -> inference server -> agent) by (model, pod)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg((rate(seldon_model_infer_seconds_total{container=\"agent\", namespace=~\"${namespace:regex}\", pod=~\"${inference_pods:regex}\", model=~\"${model:regex}\", method_type=\"rest\"}[${rate_window}])/rate(seldon_model_infer_total{container=\"agent\", namespace=~\"${namespace:regex}\", pod=~\"${inference_pods:regex}\", model=~\"${model:regex}\", method_type=\"rest\"}[${rate_window}])) > 0) by (model, pod)",
     "legendFormat": "{{model}}, {{pod}}"
    }
   ]
  },
  {
   "title": "Response throughput by model (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model) (rate(seldon_model_infer_total{namespace=~\"${namespace:regex}\", model=~\"${model:regex}\", pod=~\"${inference_pods:regex}\"}[${rate_window}]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC average latency (agent -> inference server -> agent) by (model, pod)",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 10, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg((rate(seldon_model_infer_seconds_total{container=\"agent\", namespace=~\"${namespace:regex}\", pod=~\"${inference_pods:regex}\", model=~\"${model:regex}\", method_type=\"grpc\"}[${rate_window}])/rate(seldon_model_infer_total{container=\"agent\", namespace=~\"${namespace:regex}\", pod=~\"${inference_pods:regex}\", model=~\"${model:regex}\", method_type=\"grpc\"}[${rate_window}])) > 0) by (model, pod)",
     "legendFormat": "{{model}}, {{pod}}"
    }
   ]
  },
  {
   "title": "Response throughput by inference pod, filtered by model(s) (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(seldon_model_infer_total{namespace=~\"${namespace:regex}\", model=~\"${model:regex}\", pod=~\"${inference_pods:regex}\"}[${rate_window}]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Per inference pod metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Inference latency (agent -> inference server -> agent)",
   "type": "heatmap",
   "description": "Measures latency from the time the inference server agent receives the request and the time when it gets back the inference response.",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(seldon_model_infer_api_seconds_bucket{namespace=~\"${namespace:regex}\", pod=~\"${inference_pods:regex}\"}[$__rate_interval])) by(le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference requests in-flight by inference server pod (stacked)",
   "type": "timeseries",
   "description": "Pending response futures in worker processes, per inference server pod",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 39 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(parallel_request_queue_sum{namespace=~\"${namespace:regex}\", pod=~\"${inference_pods:regex}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference latency (inference-server <-> model)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(increase(rest_server_request_duration_seconds_bucket{namespace=~\"${namespace:regex}\", pod=~\"${inference_pods:regex}\"}[$__rate_interval])) by(le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by inference pod (1000 = 1cpu, stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 51 },
   "targets": [
    {
     "expr": "sum by(pod)(rate(container_cpu_usage_seconds_total{namespace=~\"${namespace:regex}\", pod=~\"${inference_pods:regex}\"}[${rate_window}])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}