{
 "title": "Seldon Core Model Mesh Monitoring (GPU)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Models",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (seldon_loaded_model_memory_bytes_gauge{namespace=~\"^$namespace$\"} > 0 )",
     "legendFormat": "In-memory"
    },
    {
     "expr": "sum (seldon_loaded_model_gauge{namespace=~\"^$namespace$\"})",
     "legendFormat": "Registered"
    }
   ]
  },
  {
   "title": "Registered Model Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server) (seldon_loaded_model_gauge{namespace=~\"^$namespace$\"})"
    }
   ]
  },
  {
   "title": "In-Memory Model Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(server) (seldon_loaded_model_memory_bytes_gauge{namespace=~\"^$namespace$\"} > 0)"
    }
   ]
  },
  {
   "title": "In-Memory Model Replicas (Memory Slots)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server) (seldon_loaded_model_memory_bytes_gauge{namespace=~\"^$namespace$\"}) / sum by(server) (seldon_server_replica_memory_capacity_overcommit_bytes_gauge{namespace=~\"^$namespace$\"})"
    }
   ]
  },
  {
   "title": "Model Evict/Miss Rate [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(seldon_cache_evict_count{namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "Evict Rate"
    },
    {
     "expr": "sum(rate(seldon_cache_miss_count{namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "Miss Rate"
    }
   ]
  },
  {
   "title": "Model Load/Unload Rate [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum by (server) (rate(seldon_load_model_counter{namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "{{server}}_Load"
    },
    {
     "expr": "sum by (server) (rate(seldon_unload_model_counter{namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "Unloa{{server}}_Loadd"
    }
   ]
  },
  {
   "title": "GPU Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{namespace=~\"^$exported_namespace$\"}",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "CPU Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"mlserver\", namespace=~\"^$namespace$\"}) ",
     "legendFormat": "mlserver"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"triton\", namespace=~\"^$namespace$\"})",
     "legendFormat": "triton"
    }
   ]
  },
  {
   "title": "Memory Slots (triton)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(seldon_server_replica_memory_capacity_bytes_gauge{server=\"triton-gpu\", namespace=~\"^$namespace$\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(seldon_loaded_model_memory_bytes_gauge{server=\"triton-gpu\", namespace=~\"^$namespace$\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(seldon_server_replica_memory_capacity_overcommit_bytes_gauge{server=\"triton-gpu\", namespace=~\"^$namespace$\"})",
     "legendFormat": "Capacity with Over-commit"
    },
    {
     "expr": "sum(seldon_loaded_model_memory_bytes_gauge{server=\"triton-gpu\", namespace=~\"^$namespace$\"}) + sum(seldon_evicted_model_memory_bytes_gauge{server=\"triton-gpu\", namespace=~\"^$namespace$\"})",
     "legendFormat": "Used with Over-commit"
    }
   ]
  },
  {
   "title": "Memory Slots (mlserver)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(seldon_server_replica_memory_capacity_bytes_gauge{server=\"mlserver\", namespace=~\"^$namespace$\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(seldon_loaded_model_memory_bytes_gauge{server=\"mlserver\", namespace=~\"^$namespace$\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(seldon_server_replica_memory_capacity_overcommit_bytes_gauge{server=\"mlserver\", namespace=~\"^$namespace$\"})",
     "legendFormat": "Capacity with Over-commit"
    },
    {
     "expr": "sum(seldon_loaded_model_memory_bytes_gauge{server=\"mlserver\", namespace=~\"^$namespace$\"}) + sum(seldon_evicted_model_memory_bytes_gauge{server=\"mlserver\", namespace=~\"^$namespace$\"})",
     "legendFormat": "Used with Over-commit"
    }
   ]
  },
  {
   "title": "Infer Latency [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg((rate(seldon_model_aggregate_infer_seconds_total{container=\"agent\", namespace=~\"^$namespace$\"}[1m]) / rate(seldon_model_aggregate_infer_total{container=\"agent\", namespace=~\"^$namespace$\"}[1m])) > 0 ) by (server, method_type)",
     "legendFormat": "{{server}}_{{method_type}}_avg"
    }
   ]
  },
  {
   "title": "CPU [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{container=\"mlserver\", namespace=~\"^$namespace$\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate (container_cpu_usage_seconds_total{container=\"triton\", namespace=~\"^$namespace$\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}