package state_machine

import (
	"fmt"

	pb "github.com/seldonio/seldon-core/apis/go/v2/mlops/scheduler"
)

type Model interface {
	ApplyLoadModel(current ClusterState, request *pb.LoadModelRequest) (ClusterState, error)
	ApplyUnloadModel(current ClusterState, request *pb.UnloadModelRequest) (ClusterState, error)
	ApplyModelStateLoadRequested(current ClusterState) (ClusterState, error)
}

/*
	What are all the events will have to perform to change the state of the model
	- Load Models
	-
*/

// DomainEvent todo: further define the domain events
// DomainEvent represents a business-level event generated by state transitions
type DomainEvent interface {
	EventType() string
}

// ApplyLoadModel applies business logic for loading a model
// Pure function: same inputs → same outputs
func (sm *StateMachine) ApplyLoadModel(
	current ClusterState,
	request *pb.LoadModelRequest,
) (ClusterState, error) {
	modelName := request.GetModel().GetMeta().GetName()

	if modelName == "" {
		return current, fmt.Errorf("model name is empty")
	}

	// retrieve the model snap to do comparison
	futureModelState := current.generateModelSnapshot(request.GetModel())

	// calculate the future model state

	// calculate the future pipelines states
	// todo: if the model existed but its definition changed we need to update the status of a pipeline
	// todo: properly check the pipeline logic for this

	// calculate the future experiment states
	//todo: this might follow in line with the changes of pipelines

	return ClusterState{}, nil
}

func (sm *StateMachine) ApplyUnloadModel(current ClusterState, request *pb.UnloadModelRequest) (ClusterState, error) {
	//todo:

	// similarly to the load request this should mark all the models or the latest one as unloaded?

	// this will also change the status of pipelines and experiments that use the model

	panic("implement me")
	return ClusterState{}, nil
}

func (sm *StateMachine) ApplyModelStateLoadRequested(current ClusterState) (ClusterState, error) {
	//todo:

	// this will be a state transition of the model this event can also affect the status of pipelines and experiments
	// that use the model
	panic("implement me")
	return ClusterState{}, nil
}
