{
 "title": "Outlier Detection",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "# OUTLIER DETECTOR\n\n\n### Monitor predictions and performance of an Isolation Forest (IF) as outlier detector for network intrusions."
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 } },
  {
   "title": "Nb observations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "observation" }
   ]
  },
  {
   "title": "Nb Predicted Outliers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nb_outliers_tot" }
   ]
  },
  {
   "title": "% Predicted Outliers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * nb_outliers_tot / observation"
    }
   ]
  },
  {
   "title": "Nb Labeled Outliers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nb_labels_tot" }
   ]
  },
  {
   "title": "% Labeled Outliers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * nb_labels_tot / observation"
    }
   ]
  },
  {
   "title": "Outlier Prediction",
   "type": "graph",
   "description": "0=normal\n1=outlier",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Outlier" }
   ],
   "targets": [
    { "expr": "is_outlier" }
   ]
  },
  {
   "title": "Anomaly Score",
   "type": "graph",
   "description": "Anomaly score of input data. Values below the threshold line are outliers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Anomaly Score" }
   ],
   "targets": [
    { "expr": "anomaly_score" }
   ]
  },
  {
   "title": "Outlier Labels",
   "type": "graph",
   "description": "0=normal\n1=outlier",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Outlier" }
   ],
   "targets": [
    { "expr": "label" }
   ]
  },
  {
   "title": "Rolling Number of Predicted and Labeled Outliers",
   "type": "graph",
   "description": "Rolling window = 100 observations.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Number of Outliers" }
   ],
   "targets": [
    { "expr": "nb_outliers_roll", "legendFormat": "Predicted outliers" },
    { "expr": "nb_labels_roll", "legendFormat": "Labeled outliers" }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 }, "content": "# PERFORMANCE METRICS" },
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 }, "content": "### CONFUSION MATRIX" },
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 }, "content": "### OTHER METRICS" },
  {
   "title": "True Positive",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "true_positive" }
   ]
  },
  {
   "title": "False Positive",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "false_positive\n" }
   ]
  },
  {
   "title": "F1 score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "f1_tot" }
   ]
  },
  {
   "title": "Accuracy",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "accuracy_tot" }
   ]
  },
  {
   "title": "False Negative",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "false_negative" }
   ]
  },
  {
   "title": "True Negative",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "true_negative" }
   ]
  },
  {
   "title": "Precision",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "precision_tot" }
   ]
  },
  {
   "title": "Recall",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "recall_tot" }
   ]
  },
  {
   "title": "Rolling F1 and F2 Scores",
   "type": "graph",
   "description": "Rolling window = 100 observations.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "f1_roll", "legendFormat": "F1 score" },
    { "expr": "f2_roll", "legendFormat": "F2 score" }
   ]
  },
  {
   "title": "Rolling Accuracy, Precision and Recall Scores",
   "type": "graph",
   "description": "Rolling window = 100 observations.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "accuracy_roll", "legendFormat": "accuracy" },
    { "expr": "precision_roll", "legendFormat": "precision" },
    { "expr": "recall_roll", "legendFormat": "recall" }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "targets": [
    { "expr": "observation\n", "legendFormat": "Observation" },
    { "expr": "is_outlier", "legendFormat": "Outlier Prediction" },
    { "expr": "label", "legendFormat": "Outlier Label" },
    {
     "expr": "mse",
     "legendFormat": "Mean Squared Reconstruction Error"
    }
   ]
  }
 ]
}