{
 "title": "Prediction Analytics",
 "tags": [ "seldon" ],
 "time": { "to": "now", "from": "now-15m" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,deployment_name)"
   },
   {
    "name": "predictor",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,predictor_name)"
   },
   {
    "name": "version",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,predictor_version)"
   },
   {
    "name": "model_name",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_name)"
   },
   {
    "name": "model_image",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_image)"
   },
   {
    "name": "model_version",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_version)"
   }
  ]
 },
 "panels": [
  { "title": "Heading", "type": "row", "gridPos": { "y": 0, "x": 0, "w": 24, "h": 1 } },
  {
   "type": "text",
   "gridPos": { "y": 1, "x": 0, "w": 24, "h": 3 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Seldon Core API Dashboard</span>\n</div>"
  },
  { "title": "Global Counts", "type": "row", "gridPos": { "y": 4, "x": 0, "w": 24, "h": 1 } },
  {
   "title": "Global Request Rate",
   "type": "singlestat",
   "gridPos": { "y": 5, "x": 0, "w": 6, "h": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_executor_server_requests_seconds_count[1m])),0.001)"
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "y": 5, "x": 6, "w": 6, "h": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_server_requests_seconds_count{status!~\"5.*\"}[1m])) / sum(rate(seldon_api_executor_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "y": 5, "x": 12, "w": 6, "h": 3 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_executor_server_requests_seconds_count{status=~\"4.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "singlestat",
   "gridPos": { "y": 5, "x": 18, "w": 6, "h": 3 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_executor_server_requests_seconds_count{status=~\"5.*\"}[1m])) "
    }
   ]
  },
  { "title": "Deployment Counts", "type": "row", "gridPos": { "y": 8, "x": 0, "w": 24, "h": 1 }, "repeat": "deployment" },
  {
   "title": "Request Rate ($deployment)",
   "type": "singlestat",
   "gridPos": { "y": 9, "x": 0, "w": 6, "h": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_executor_client_requests_seconds_count{deployment_name=~'$deployment'}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success ($deployment)",
   "type": "singlestat",
   "gridPos": { "y": 9, "x": 6, "w": 6, "h": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\",status!~\"5.*\"}[1m])) / sum(rate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs ($deployment)",
   "type": "singlestat",
   "gridPos": { "y": 9, "x": 12, "w": 6, "h": 3 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\",status=~\"4.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xxs ($deployment)",
   "type": "singlestat",
   "gridPos": { "y": 9, "x": 18, "w": 6, "h": 3 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\",status=~\"5.*\"}[1m]))"
    }
   ]
  },
  { "title": "Models", "type": "row", "gridPos": { "y": 12, "x": 0, "w": 24, "h": 1 } },
  {
   "type": "text",
   "gridPos": { "y": 13, "x": 0, "w": 24, "h": 3 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Models</span>\n</div>"
  },
  { "title": "Model Metrics", "type": "row", "gridPos": { "y": 16, "x": 0, "w": 24, "h": 1 }, "repeat": "model_image" },
  {
   "title": "Reqs/sec to $model_image",
   "type": "graph",
   "gridPos": { "y": 17, "x": 0, "w": 8, "h": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}}",
     "expr": "sum(rate(seldon_api_executor_client_requests_seconds_count{model_name=~\"$model_name\",model_version=~\"$model_version\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[5s])) by (model_name,predictor_name,predictor_version,model_image,model_version,service)"
    }
   ]
  },
  {
   "title": "$model_image Reward",
   "type": "graph",
   "gridPos": { "y": 17, "x": 8, "w": 8, "h": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "legendFormat": "{{deployment_name}}/{{predictor_name}}:{{predictor_version}}  {{model_name}} {{model_image}} : {{model_version}}",
     "expr": "rate(seldon_api_model_feedback_reward_total{deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_image=~\"$model_image\",model_version=~\"$model_version\",model_name=~\"$model_name\"}[1m])/rate(seldon_api_model_feedback_total{deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_image=~\"$model_image\",model_version=~\"$model_version\",model_name=~\"$model_name\"}[1m])"
    }
   ]
  },
  {
   "title": "$model_image Latency",
   "type": "graph",
   "gridPos": { "y": 17, "x": 16, "w": 8, "h": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}: {{model_version}} (p50)",
     "expr": "histogram_quantile(0.5, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\"/Predict\", model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[20s])) by (predictor_name,predictor_version,model_name,model_image,model_version,le))"
    },
    {
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p75)",
     "expr": "histogram_quantile(0.75, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[20s])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))"
    },
    {
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}}  {{service}} (p90)",
     "expr": "histogram_quantile(0.9, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[20s])) by (predictor_name,predictor_version,model_name,model_image,model_version, service,le))"
    },
    {
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p95)",
     "expr": "histogram_quantile(0.95, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[20s])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))"
    },
    {
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p99)",
     "expr": "histogram_quantile(0.99, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[20s])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))"
    }
   ]
  }
 ]
}