# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class ByteData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsByteData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ByteData()
        x.Init(buf, n + offset)
        return x

    # ByteData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ByteData
    def BinData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ByteData
    def BinDataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # ByteData
    def BinDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ByteDataStart(builder): builder.StartObject(1)
def ByteDataAddBinData(builder, binData): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(binData), 0)
def ByteDataStartBinDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def ByteDataEnd(builder): return builder.EndObject()
