#!/bin/bash

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo ">>> Cleanup Model..."
kubectl delete -f $SCRIPT_DIR/manifests/model --ignore-not-found=true
