#!/bin/bash

# Source: https://docs.seldon.io/projects/seldon-core/en/latest/charts/seldon-core-operator.html

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

SELDON_CORE_IMAGE_TAG_DEFAULT=`cat ~/.seldon-core-image-tag`

SELDON_CORE_IMAGE_TAG=${SELDON_CORE_IMAGE_TAG:-$SELDON_CORE_IMAGE_TAG_DEFAULT}

echo ">>> Creating namespace..."
kubectl create namespace seldon-system

echo ">>> Installing Seldon Core ${SELDON_CORE_IMAGE_TAG}..."
helm upgrade --install seldon-core seldon-core-operator \
    --repo https://storage.googleapis.com/seldon-charts \
    --set usageMetrics.enabled=true \
    --set istio.enabled=false \
    --set keda.enabled=false \
    --set executor.image.registry="quay.io" \
    --set executor.image.repository="domino/seldon-core-executor" \
    --set executor.image.tag="${SELDON_CORE_IMAGE_TAG}" \
    --set image.registry="quay.io" \
    --set image.repository="domino/seldon-core-operator" \
    --set image.tag="${SELDON_CORE_IMAGE_TAG}" \
    --namespace seldon-system

echo ">>> Creating domino-quay-repos secret for pulling Domino docker images..."
kubectl create secret -n seldon-system docker-registry domino-quay-repos \
  --docker-username="${DOCKER_USERNAME}" \
  --docker-password="${DOCKER_PASSWORD}" \
  --docker-server="${DOCKER_REGISTRY}"

echo ">>> Patching seldon-controller-manager to add imagePullSecrets..."
kubectl patch deployment seldon-controller-manager -n seldon-system -p '{ "spec": { "template": { "spec": { "imagePullSecrets": [ { "name": "domino-quay-repos" } ] } } } }'

echo ">>> Done installing Seldon Core."
