#!/bin/bash

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

$SCRIPT_DIR/install-test-namespace

$SCRIPT_DIR/install-seldon-core-dev

$SCRIPT_DIR/install-rabbitmq

$SCRIPT_DIR/setup-model
