#!/bin/bash

# Source: https://strimzi.io/quickstarts/

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo ">>> Creating namespace..."
kubectl create namespace kafka

echo ">>> Creating RBAC resources..."
kubectl apply -f $SCRIPT_DIR/manifests/kafka -n kafka

echo ">>> Creating Kafka definitions..."
kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka

echo ">>> Creating Kafka cluster..."
kubectl apply -f https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml -n kafka

echo ">>> Waiting for Kafka cluster to become ready (this may take a few minutes)..."
kubectl wait kafka/my-cluster --for=condition=Ready --timeout=600s -n kafka

echo ">>> Done installing Kafka."
