#!/bin/bash

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo ">>> Updating helm repo..."
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm repo update

echo ">>> Creating namespace..."
kubectl create namespace istio-system

echo ">>> Creating RBAC resources..."
kubectl apply -f $SCRIPT_DIR/manifests/istio -n istio-system

echo ">>> Installing Istio base..."
helm install istio-base istio/base -n istio-system

echo ">>> Installing istiod..."
helm install istiod istio/istiod -n istio-system --wait

echo ">>> Installing Istio ingress gateway..."
helm install istio-ingressgateway istio/gateway -n istio-system --wait

echo ">>> Done installing Istio."
