#!/bin/bash

COMPUTE_NAMESPACE=seldon-regression-test

echo ">>> Testing iris model..."
kubectl -n $COMPUTE_NAMESPACE exec deployments/iris-model-default-0-classifier -c classifier -- curl -X POST http://localhost:8000/api/v1.0/predictions -H 'Content-Type: application/json' -d '{"data": {"ndarray": [[1,2,3,4]] }}'

echo ">>> Testing mock classifier model..."
kubectl -n $COMPUTE_NAMESPACE exec deployments/mock-classifier-model-0-classifier -c classifier -- curl -X POST http://localhost:8000/api/v1.0/predictions -H 'Content-Type: application/json' -d '{"data": {"ndarray": [[1.0, 2.0, 5.0]] }}'

#echo ">>> Testing domino model..."
#curl -X POST http://localhost:8080/seldon/${COMPUTE_NAMESPACE}/model-62e40a364c6cd60f752c38f9/api/v1.0/predictions -H 'Content-Type: application/json' -d '{ "data": { "ndarray": [[0,1]] } }'
