#!/usr/bin/env bash
#
# add-pr-build-comment
#
set -o nounset
set -o errexit
set -o pipefail
set -o noclobber
set -o noglob
set -o xtrace

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

REPO_OWNER=${REPO_OWNER}
REPO_NAME=${REPO_NAME}
PULL_NUMBER=${PULL_NUMBER}
BUILD_NUMBER=${BUILD_NUMBER}
PIPELINE_CONTEXT=${PIPELINE_CONTEXT}

COMMENT_MSG=$(cat <<EOF
# STARTING TEST [ ${PIPELINE_CONTEXT} # ${BUILD_NUMBER} ]

Logs will be available when test completes in the following link:
https://github.com/${REPO_OWNER}/${REPO_NAME}/blob/gh-pages/jenkins-x/logs/${REPO_OWNER}/${REPO_NAME}/PR-${PULL_NUMBER}/${BUILD_NUMBER}.log

impatient try
```
jx get build logs ${REPO_OWNER}/${REPO_NAME}/PR-${PULL_NUMBER} --build=${BUILD_NUMBER}
```
EOF
)

jx step pr comment --owner=${REPO_OWNER} --repository=${REPO_NAME} --pull-request=${PULL_NUMBER} --comment="${COMMENT_MSG}"

