#!/usr/bin/env bash
#
# add-pr-build-comment
#
set -o nounset
set -o errexit
set -o pipefail
set -o noclobber
set -o noglob
set -o xtrace

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

REPO_OWNER=${REPO_OWNER}
REPO_NAME=${REPO_NAME}
PULL_NUMBER=${PULL_NUMBER}
BUILD_NUMBER=${BUILD_NUMBER}
PIPELINE_CONTEXT=${PIPELINE_CONTEXT}

COMMENT_MSG=$(cat <<EOF
# SUCCESS [${PIPELINE_CONTEXT} #${BUILD_NUMBER}] ✅

Well done! 😎
EOF
)

jx step pr comment --owner=${REPO_OWNER} --repository=${REPO_NAME} --pull-request=${PULL_NUMBER} --comment="${COMMENT_MSG}"

