#!/usr/bin/env bash
#
# add-pr-build-comment
#
set -o nounset
set -o pipefail
set -o noclobber
set -o noglob
set -o xtrace


set +o errexit

(cd ../python && snyk test)
PYTHON_CHECKS=$?

(cd ../operator && snyk test)
OPERATOR_CHECKS=$?

(cd ../executor && snyk test)
EXECUTOR_CHECKS=$?

set -o errexit

echo "Python exit value: $PYTHON_EXIT_VALUE"
echo "Operator exit value: $OPERATOR_CHECKS"
echo "Executor exit value: $EXECUTOR_CHECKS"

exit $((${PYTHON_CHECKS} \
    + ${OPERATOR_CHECKS} \
    + ${EXECUTOR_CHECKS}))

