FROM seldonio/pyseldon2:3.1

RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential

RUN mkdir microservice
COPY ./* /microservice/
WORKDIR /microservice

RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["python","rest_microservice.py","{model_name}"]