.PHONY: install-requirements
install-requirements:
	pip install -r requirements.txt
	jupyter nbextension enable --py widgetsnbextension

.PHONY: install-ffmpeg-ubuntu
install-ffmpeg-ubuntu:
	sudo apt-get install ffmpeg
