#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

${KUBECTL} delete secret generic github-credentials -n jenkins --ignore-not-found

