#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/settings.sh

IMAGE_VERSION=k8s_v1.14.0
IMAGE_NAME="seldonio/k8s-deployer"

docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "${K8S_MANIFEST_FILES_DIR}:/cicd-demo-k8s-manifest-files" \
    ${IMAGE_NAME}:${IMAGE_VERSION} sh

