#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/settings.sh

IMAGE_VERSION=0.1
IMAGE_NAME="gsunner/s2i-tools"

docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "${MODEL_SOURCE_FILES_DIR}:/cicd-demo-model-source-files" \
    ${IMAGE_NAME}:${IMAGE_VERSION} sh

