#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

source ${STARTUP_DIR}/settings.sh

KUBECTL="kubectl --context=${KUBE_CONTEXT}"

${KUBECTL} rollout status deployment.apps/argo-ui -n argo -w
${KUBECTL} rollout status deployment.apps/workflow-controller -n argo -w
${KUBECTL} rollout status deployment.apps/activity-monitor-deployment -n default -w
${KUBECTL} rollout status deployment.apps/docker-private-registry-deployment -n default -w
${KUBECTL} rollout status deployment/seldon-controller-manager -n seldon-system -w
${KUBECTL} rollout status deployment.apps/ambassador

${KUBECTL} rollout status deployment.apps/argocd-application-controller -n argocd -w
${KUBECTL} rollout status deployment.apps/argocd-repo-server -n argocd -w
${KUBECTL} rollout status deployment.apps/argocd-server -n argocd -w
${KUBECTL} rollout status deployment.apps/argocd-dex-server -n argocd -w

${KUBECTL} rollout status deployment.apps/jenkins -n jenkins -w

