
# https://github.com/strimzi/strimzi-kafka-operator/tree/master/helm-charts/strimzi-kafka-operator
install:
	helm install my-release strimzi/strimzi-kafka-operator


create_cluster:
	kubectl create -f cluster.yaml

create_topic:
	kubectl create -f topic.yaml

