#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail
set -o noclobber
set -o noglob

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

if [[ $# < 1 ]]; then
    echo "Need image name"
    exit 1
fi

IMAGE_NAME=$1

curl -X GET "http://127.0.0.1:5000/v2/${IMAGE_NAME}/tags/list"

