// Code generated by "stringer -type=PipelineStatus"; DO NOT EDIT.

package pipeline

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PipelineStatusUnknown-0]
	_ = x[PipelineCreate-1]
	_ = x[PipelineCreating-2]
	_ = x[PipelineReady-3]
	_ = x[PipelineFailed-4]
	_ = x[PipelineTerminate-5]
	_ = x[PipelineTerminating-6]
	_ = x[PipelineTerminated-7]
	_ = x[PipelineRebalancing-8]
	_ = x[PipelineFailedTerminating-9]
}

const _PipelineStatus_name = "PipelineStatusUnknownPipelineCreatePipelineCreatingPipelineReadyPipelineFailedPipelineTerminatePipelineTerminatingPipelineTerminatedPipelineRebalancingPipelineFailedTerminating"

var _PipelineStatus_index = [...]uint8{0, 21, 35, 51, 64, 78, 95, 114, 132, 151, 176}

func (i PipelineStatus) String() string {
	if i >= PipelineStatus(len(_PipelineStatus_index)-1) {
		return "PipelineStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipelineStatus_name[_PipelineStatus_index[i]:_PipelineStatus_index[i+1]]
}
